version: '3'

services:
  barcode-pdf-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production 